## Create a destination directory
if(!file.exists("./data1")){dir.create("./data1")}
## Download the data into the directory
fileUrl<-"https://d396qusza40orc.cloudfront.net/
getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(fileUrl, destfile="./data1/proyect.zip")
proyectData <- read.csv("./data1/proyect.zip")
unzip<-unzip("./data1/proyect.zip")

## Read the data
X_train<-read.csv("./train/X_train.txt", header=FALSE)

subject_train<-read.csv("./train/subject_train.txt")

y_train<-read.csv("./train/y_train.txt", header=FALSE)

y_test<-read.csv("./test/y_test.txt", header=FALSE)
X_test<-read.csv("./test/X_test.txt", header=FALSE)
subject_test<-read.csv("./test/subject_test.txt", header=FALSE)

## Combine the data
y_testtrain<-rbind(y_test,y_train)
subject_testtrain<-rbind(subject_test,subject_train)

##Extract the measurements on the mean and standard deviation for each measurement.

X_testvar<-read.csv("./X_test.txt",sep=" ",dec=".",header=FALSE)
testmeanstd<-X_testvar[,3:8]
X_trainvar<-read.csv("./train/X_train.txt",sep=" ",dec=".",header=FALSE)
trainmeanstd<-X_trainvar[,3:8]
testtrainmeanstd<-rbind(meanstd,trainmeanstd)

X_trainprueba<-read.table("./train/X_train.txt",comment.char = "",colClasses="numeric")

X_testtrain2<-rbind(X_testprueba,X_trainprueba)

dataset=cbind(subject_testtrain,X_testtrain2,y_testtrain)

## Assign apropiately names to the variables
featurescol2<-features[,2]
featuresTT<-featurescol2=="mean()"|featurescol2=="std()"
X_testtrainTT<-X_testtrain2[,featuresTT]
features[featuresTT,]

featuresbycol<-features[featuresTT,]
names(X_testtrainTT)<-featuresbycol[,1]

for (i in 1:nrow(y_testtrain)) {
        if (y_testtrain[i,1]==1){y_testtrain[i,1]="WALKING"}
        else if (y_testtrain[i,1]==2) {y_testtrain[i,1]="WALKING_UPSTAIRS"}
        else if (y_testtrain[i,1]==3) {y_testtrain[i,1]="WALKING_DOWNSTAIRS"}
        else if (y_testtrain[i,1]==4) {y_testtrain[i,1]="SITTING"}
        else if (y_testtrain[i,1]==5) {y_testtrain[i,1]="STANDING"}
        else if (y_testtrain[i,1]==6) {y_testtrain[i,1]="LAYING"}
}
names(y_testtrain)<-"ACTIVITY"
names(subject_testtrain)<-"SUBJECT"

X_testtrain<-rbind(X_test,X_train)

write.table(X_testtrain,file="tidy.txt", row.names=FALSE)

## Create a 2nd, independent tidy data set with the average of each variable for each activity and each subject.

da<-ddply(todos,.(SUBJECT, ACTIVITY),summarize, mean=(mean(dataset[,2])))
